// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiseBet.backend.Data;

#nullable disable

namespace WiseBet.backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WiseBet.backend.Models.BetHistory", b =>
                {
                    b.Property<Guid>("BetHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BetPossibilityID")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserAccountUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BetHistoryID");

                    b.HasIndex("BetPossibilityID");

                    b.HasIndex("RoundID");

                    b.HasIndex("UserAccountUserID");

                    b.ToTable("BetHistories");
                });

            modelBuilder.Entity("WiseBet.backend.Models.BetPossibility", b =>
                {
                    b.Property<int>("BetPossibilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetPossibilityID"));

                    b.Property<string>("BetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BetPossibilityID");

                    b.ToTable("BetPossibilities");
                });

            modelBuilder.Entity("WiseBet.backend.Models.Chat", b =>
                {
                    b.Property<Guid>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeOfChat")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("chat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatID");

                    b.HasIndex("UserID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("WiseBet.backend.Models.PaymentHistory", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentAmount")
                        .HasColumnType("int");

                    b.Property<int>("PrePaymentBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfPayment")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("PaymentHistories");
                });

            modelBuilder.Entity("WiseBet.backend.Models.Round", b =>
                {
                    b.Property<Guid>("RoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Made")
                        .HasColumnType("int");

                    b.Property<int>("Payout")
                        .HasColumnType("int");

                    b.Property<DateTime>("RoundDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RoundResultID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("RoundID");

                    b.HasIndex("RoundResultID");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WiseBet.backend.Models.RoundResult", b =>
                {
                    b.Property<Guid>("RoundResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoundResultID");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("WiseBet.backend.Models.UserAccount", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("WiseBet.backend.Models.BetHistory", b =>
                {
                    b.HasOne("WiseBet.backend.Models.BetPossibility", "BetPossibility")
                        .WithMany("Bets")
                        .HasForeignKey("BetPossibilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WiseBet.backend.Models.Round", "Round")
                        .WithMany("Bets")
                        .HasForeignKey("RoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WiseBet.backend.Models.UserAccount", "UserAccount")
                        .WithMany("BetHistories")
                        .HasForeignKey("UserAccountUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BetPossibility");

                    b.Navigation("Round");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WiseBet.backend.Models.Chat", b =>
                {
                    b.HasOne("WiseBet.backend.Models.UserAccount", "UserAccount")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WiseBet.backend.Models.PaymentHistory", b =>
                {
                    b.HasOne("WiseBet.backend.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WiseBet.backend.Models.Round", b =>
                {
                    b.HasOne("WiseBet.backend.Models.RoundResult", null)
                        .WithMany("Round")
                        .HasForeignKey("RoundResultID");
                });

            modelBuilder.Entity("WiseBet.backend.Models.BetPossibility", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("WiseBet.backend.Models.Round", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("WiseBet.backend.Models.RoundResult", b =>
                {
                    b.Navigation("Round");
                });

            modelBuilder.Entity("WiseBet.backend.Models.UserAccount", b =>
                {
                    b.Navigation("BetHistories");

                    b.Navigation("ChatHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
